<?php

namespace Proxies\__CG__\ZonaComix\WebsiteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \ZonaComix\WebsiteBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'readings', 'revenue', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'referral', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'referrals', 'comics', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'followers', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'users_following', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'comics_following', 'id', 'register_date', 'username', 'email', 'password', 'display_name', 'phrase', 'premium_expire', 'active', 'website', 'facebook', 'twitter', 'google', 'tumblr', 'deviantART', 'youtube', 'referral_expire');
        }

        return array('__isInitialized__', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'readings', 'revenue', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'referral', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'referrals', 'comics', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'followers', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'users_following', '' . "\0" . 'ZonaComix\\WebsiteBundle\\Entity\\User' . "\0" . 'comics_following', 'id', 'register_date', 'username', 'email', 'password', 'display_name', 'phrase', 'premium_expire', 'active', 'website', 'facebook', 'twitter', 'google', 'tumblr', 'deviantART', 'youtube', 'referral_expire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegisterDate($registerDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegisterDate', array($registerDate));

        return parent::setRegisterDate($registerDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisterDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisterDate', array());

        return parent::getRegisterDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', array($displayName));

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhrase($phrase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhrase', array($phrase));

        return parent::setPhrase($phrase);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhrase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhrase', array());

        return parent::getPhrase();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremiumExpire($premiumExpire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremiumExpire', array($premiumExpire));

        return parent::setPremiumExpire($premiumExpire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremiumExpire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremiumExpire', array());

        return parent::getPremiumExpire();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebook));

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogle($google)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogle', array($google));

        return parent::setGoogle($google);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogle', array());

        return parent::getGoogle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTumblr($tumblr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTumblr', array($tumblr));

        return parent::setTumblr($tumblr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTumblr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTumblr', array());

        return parent::getTumblr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviantART($deviantART)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviantART', array($deviantART));

        return parent::setDeviantART($deviantART);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviantART()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviantART', array());

        return parent::getDeviantART();
    }

    /**
     * {@inheritDoc}
     */
    public function setYoutube($youtube)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYoutube', array($youtube));

        return parent::setYoutube($youtube);
    }

    /**
     * {@inheritDoc}
     */
    public function getYoutube()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYoutube', array());

        return parent::getYoutube();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferralExpire($referralExpire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferralExpire', array($referralExpire));

        return parent::setReferralExpire($referralExpire);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferralExpire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferralExpire', array());

        return parent::getReferralExpire();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevenue(\ZonaComix\WebsiteBundle\Entity\Revenue $revenue = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevenue', array($revenue));

        return parent::setRevenue($revenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenue', array());

        return parent::getRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferral(\ZonaComix\WebsiteBundle\Entity\User $referral = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferral', array($referral));

        return parent::setReferral($referral);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferral', array());

        return parent::getReferral();
    }

    /**
     * {@inheritDoc}
     */
    public function addReferral(\ZonaComix\WebsiteBundle\Entity\User $referrals)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReferral', array($referrals));

        return parent::addReferral($referrals);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReferral(\ZonaComix\WebsiteBundle\Entity\User $referrals)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReferral', array($referrals));

        return parent::removeReferral($referrals);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferrals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferrals', array());

        return parent::getReferrals();
    }

    /**
     * {@inheritDoc}
     */
    public function addComic(\ZonaComix\WebsiteBundle\Entity\Comic $comics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComic', array($comics));

        return parent::addComic($comics);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComic(\ZonaComix\WebsiteBundle\Entity\Comic $comics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComic', array($comics));

        return parent::removeComic($comics);
    }

    /**
     * {@inheritDoc}
     */
    public function getComics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComics', array());

        return parent::getComics();
    }

    /**
     * {@inheritDoc}
     */
    public function addFollower(\ZonaComix\WebsiteBundle\Entity\User $followers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFollower', array($followers));

        return parent::addFollower($followers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFollower(\ZonaComix\WebsiteBundle\Entity\User $followers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFollower', array($followers));

        return parent::removeFollower($followers);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowers', array());

        return parent::getFollowers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersFollowing(\ZonaComix\WebsiteBundle\Entity\User $usersFollowing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersFollowing', array($usersFollowing));

        return parent::addUsersFollowing($usersFollowing);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersFollowing(\ZonaComix\WebsiteBundle\Entity\User $usersFollowing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersFollowing', array($usersFollowing));

        return parent::removeUsersFollowing($usersFollowing);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersFollowing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersFollowing', array());

        return parent::getUsersFollowing();
    }

    /**
     * {@inheritDoc}
     */
    public function addComicsFollowing(\ZonaComix\WebsiteBundle\Entity\Comic $comicsFollowing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComicsFollowing', array($comicsFollowing));

        return parent::addComicsFollowing($comicsFollowing);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComicsFollowing(\ZonaComix\WebsiteBundle\Entity\Comic $comicsFollowing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComicsFollowing', array($comicsFollowing));

        return parent::removeComicsFollowing($comicsFollowing);
    }

    /**
     * {@inheritDoc}
     */
    public function getComicsFollowing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComicsFollowing', array());

        return parent::getComicsFollowing();
    }

    /**
     * {@inheritDoc}
     */
    public function addReading(\ZonaComix\WebsiteBundle\Entity\Reading $readings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReading', array($readings));

        return parent::addReading($readings);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReading(\ZonaComix\WebsiteBundle\Entity\Reading $readings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReading', array($readings));

        return parent::removeReading($readings);
    }

    /**
     * {@inheritDoc}
     */
    public function getReadings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReadings', array());

        return parent::getReadings();
    }

}
